# site settings
title: Aditya Iyengar
subtitle:
email: adityaiyengar@iitb.ac.in
description: Welcome to my personal webpage!
baseurl: #"/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Room 7, Hostel 5, IIT Bombay
city: Mumbai
state: MH
zip_code: 400076
country: India
phone: '+(91) 78880 44850'

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/aditya.iyengar.50/
github_url: https://github.com/iyengaraditya
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/atinygrayidea_/
linkedin_url: https://www.linkedin.com/in/aditya-iyengar-096729184/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
